common/models/TestPerson.php
<?php

namespace common\models;

use Yii;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use yii\behaviors\TimestampBehavior;

/**
 * @property int $id
 * @property string|null $surname
 * @property int|null $age
 * @property int|null $gender
 * @property int|null $country
 * @property int|null $level_of_education
 * @property int|null $type_of_education
 * @property int|null $is_art_education
 * @property int|null $type_of_device
 * @property string|null $array_of_questions_json
 * @property string|null $array_of_dop_stim_0_json
 * @property string|null $array_of_dop_stim_1_json
 * @property string|null $array_of_dop_stim_1_1_json
 * @property int|null $number_of_answer
 * @property string|null $personal_token
 * @property string $auth_key
 * @property int|null $created_at
 * @property int|null $updated_at
 * @property int|null $is_deleted
 * @property int|null $deleted_at
 
 * @property TestAnswer[] $testAnswers
 * 
 * @property-read array $arrayOfQuestions
 */
class TestPerson extends ActiveRecord implements IdentityInterface
{
    const AGE_00_13 = 1;
    const AGE_14_17 = 2;
    const AGE_18_24 = 3;
    const AGE_25_34 = 4;
    const AGE_35_44 = 5;
    const AGE_45_59 = 6;
    const AGE_60_00 = 7;
    
	const GENDER_MALE = 0;
	const GENDER_FEMALE = 1;
    const GENDER_OTHER = 10;
	
	const COUNTRY_RUSSIA = 7;
	const COUNTRY_USA = 1;
	const COUNTRY_UK = 44;
	const COUNTRY_GERMANY = 49;
	const COUNTRY_SPAIN = 34;
	const COUNTRY_ITALY = 39;
	const COUNTRY_CHINA = 86;
	const COUNTRY_KOREA = 82;
	const COUNTRY_FINLAND = 358;
	const COUNTRY_FRANCE = 33;
	const COUNTRY_JAPAN = 81;
	const COUNTRY_OTHER = -1;
    
    const COLOR_BLIND_NOT = 0;
    const COLOR_BLIND_GREEN_RED = 1;
    const COLOR_BLIND_BLUE_GREEN = 2;
	
	const LEVEL_WITHOUT = 0;
	const LEVEL_SECONDARY = 2;
	const LEVEL_INCOMPLETE_HIGHER = 4;
	const LEVEL_HIGHER = 6;
	
	const TYPE_WITHOUT = 0;
	const TYPE_TECHNICAL = 1;
	const TYPE_HUMANITARIAN = 3;
	
	const DEVICE_PC = 1;
	const DEVICE_TABLET = 2;
	const DEVICE_SMART = 3;

	/**
     * {@inheritdoc}
     */
	public static function tableName()
    {
        return '{{test_persons}}';
    }
	
	/**
     * {@inheritdoc}
     */
	public function rules()
    {
        return [
			['surname', 'string', 'min' => 2, 'max' => 100],
			//['age', 'number','min' => 8, 'max' => 108],
            ['age', 'in', 'range' => array_keys(static::getAgesArray())],
			[
                [
                    'gender',
                    'country',
                    'level_of_education',
                    'type_of_education',
                    'is_art_education',
                    'type_of_device',
                ], 
                'integer'
            ],
			['gender', 'in', 'range' => array_keys(static::getGendersArray())],
			['country', 'in', 'range' => array_keys(static::getCountriesArray())],
            ['color_blindness', 'in', 'range' => array_keys(static::getColorBlindnessArray())],
			['level_of_education', 'in', 'range' => array_keys(static::getLevelsOfEducationArray())],
			['type_of_education', 'in', 'range' => array_keys(static::getTypesOfEducationArray())],
			['is_art_education', 'in', 'range' => array_keys(static::getYesNoArray())],
			['type_of_device', 'in', 'range' => array_keys(static::getDevicesArray())],
			[
                [
                    'surname',
                    'age',
                    'gender',
                    'country',
                    'level_of_education',
                    'type_of_education',
                    'is_art_education',
                    'type_of_device',
                ],
                'required'
            ],
        ];
    }
	
	/**
     * {@inheritdoc}
     */
	public function attributeLabels()
	{
		return [
			'surname' => Yii::t('frontend', 'Surname or Nickname'),
			'age' => Yii::t('frontend', 'Age'),
			'gender' => Yii::t('frontend', 'Gender'),
			'country' => Yii::t('frontend', 'Country'),
            'color_blindness' => Yii::t('frontend', 'Color blindness'),
			'level_of_education' => Yii::t('frontend', 'The level of Education'),
			'type_of_education' => Yii::t('frontend', 'Type of Education'),
			'is_art_education' => Yii::t('frontend', 'The presence of art Education'),
			'type_of_device' => Yii::t('frontend', 'Type of device you are testing from'),
		];
	}
    
    public function behaviors()
	{
		return [
            ['class' => TimestampBehavior::class],
		];
	}
	
    public static function getAgesArray() : array
	{
		return [
			self::AGE_00_13 => Yii::t('frontend', '< 14'),
			self::AGE_14_17 => Yii::t('frontend', '14 - 17'),
            self::AGE_18_24 => Yii::t('frontend', '18 - 24'),
            self::AGE_25_34 => Yii::t('frontend', '25 - 34'),
            self::AGE_35_44 => Yii::t('frontend', '35 - 44'),
			self::AGE_45_59 => Yii::t('frontend', '45 - 59'),
            self::AGE_60_00 => Yii::t('frontend', '60+'),
		];
	}
    
    public function getAgeString()
	{
		return $this->age > 7 ? $this->age . ' (old)' : $this->getAgesArray()[$this->age];
	}
    
	public static function getGendersArray() : array
	{
		return [
			self::GENDER_MALE => Yii::t('frontend', 'Male'),
			self::GENDER_FEMALE => Yii::t('frontend', 'Female'),
            self::GENDER_OTHER => Yii::t('frontend', 'Other'),
		];
	}
	
	public static function getCountriesArray() : array
	{
		return [
			self::COUNTRY_RUSSIA => Yii::t('frontend', 'Russia'),
			self::COUNTRY_USA => Yii::t('frontend', 'USA'),
			self::COUNTRY_UK => Yii::t('frontend', 'United Kingdom'),
			self::COUNTRY_GERMANY => Yii::t('frontend', 'Germany'),
			self::COUNTRY_SPAIN => Yii::t('frontend', 'Spain'),
			self::COUNTRY_ITALY => Yii::t('frontend', 'Italy'),
			self::COUNTRY_CHINA => Yii::t('frontend', 'China'),
			self::COUNTRY_KOREA => Yii::t('frontend', 'Korea'),
			self::COUNTRY_FINLAND => Yii::t('frontend', 'Finland'),
			self::COUNTRY_FRANCE => Yii::t('frontend', 'France'),
			self::COUNTRY_JAPAN => Yii::t('frontend', 'Japan'),
			self::COUNTRY_OTHER => Yii::t('frontend', 'other'),
		];
	}
    
    public static function getColorBlindnessArray() : array
    {
        return [
            self::COLOR_BLIND_NOT => Yii::t('frontend', 'No'),
            self::COLOR_BLIND_GREEN_RED => Yii::t('frontend', 'Green - Red'),
            self::COLOR_BLIND_BLUE_GREEN => Yii::t('frontend', 'Blue - Green'),
        ];
    }
	
	public static function getLevelsOfEducationArray() : array
	{
		return [
			self::LEVEL_WITHOUT => Yii::t('frontend', 'Without education'),
			self::LEVEL_SECONDARY => Yii::t('frontend', 'Secondary education'),
			self::LEVEL_INCOMPLETE_HIGHER => Yii::t('frontend', 'Unfinished higher education'),
			self::LEVEL_HIGHER => Yii::t('frontend', 'Higher education'),
		];
	}
	
	public static function getTypesOfEducationArray() : array
	{
		return [
			self::TYPE_WITHOUT => \Yii::t('frontend', 'Without type'),
			self::TYPE_TECHNICAL => \Yii::t('frontend', 'Technical education'),
			self::TYPE_HUMANITARIAN => \Yii::t('frontend', 'Humanitarian education'),
		];
	}
	
	public static function getYesNoArray() : array
	{
		return [
			1 => \Yii::t('frontend', 'Yes'),
			0 => \Yii::t('frontend', 'No'),
		];
	}

	public static function getDevicesArray() : array
	{
		return [
			self::DEVICE_PC => \Yii::t('frontend', 'Personal Computer'),
			self::DEVICE_TABLET => \Yii::t('frontend', 'Tablet'),
			self::DEVICE_SMART => \Yii::t('frontend', 'Smartphone'),
		];
	}
    
    /**
     * {@inheritdoc}
     */
	public function beforeSave($insert)
	{
        $isAnime = Yii::$app->params['testVersion'] === 'anime';
        $numberOfQuestions = Yii::$app->params['numberOfQuestions'];
		if ($insert) {
            $this->color_blindness = $this->color_blindness ?: self::COLOR_BLIND_NOT;
            
			$this->generateAuthKey();
			$this->personal_token = Yii::$app->security->generateRandomString(32);
			
			$arrayOfQuestions = range(1, $numberOfQuestions);
			shuffle($arrayOfQuestions);
			$this->array_of_questions_json = json_encode(array_merge([0], $arrayOfQuestions));
            
            if ($isAnime) {
                $arrayOfDopStim0 = range(1, 26);
            } else {
                $arrayOfDopStim0 = range(1, 25);
            }
			shuffle($arrayOfDopStim0);
			$this->array_of_dop_stim_0_json = json_encode(array_merge([0], $arrayOfDopStim0));
            
            $arrayOfDopStim1 = range(1, 25);
			shuffle($arrayOfDopStim1);
			$this->array_of_dop_stim_1_json = json_encode(array_merge([0], $arrayOfDopStim1));
            
            if ($isAnime) {
                $arrayOfDopStim11 = range(26, 54);
            } else {
                $arrayOfDopStim11 = range(26, 54);
                unset($arrayOfDopStim11['21']);
                $arrayOfDopStim11 = array_values($arrayOfDopStim11);
            }
			shuffle($arrayOfDopStim11);
			$this->array_of_dop_stim_1_1_json = json_encode(array_merge([0], $arrayOfDopStim11));
		}
		return parent::beforeSave($insert);
	}
    
    /**
     * Gets query for [[TestAnswer]].
     *
     * @return \yii\db\ActiveQuery
     */
	public function getTestAnswers()
    {
        return $this->hasMany(TestAnswer::class, ['test_person_id' => 'id'])->inverseOf('testPerson');
    }
    
    /**
     * @return integer[]
     */
	public function getArrayOfQuestions() : array
	{
		return (array) json_decode($this->array_of_questions_json, true);
	}
    
    public function getArrayOfDopStim0() : array
	{
		return (array) json_decode($this->array_of_dop_stim_0_json, true);
	}
    
    public function getArrayOfDopStim1() : array
	{
		return (array) json_decode($this->array_of_dop_stim_1_json, true);
	}
    
    public function getArrayOfDopStim11() : array
	{
		return (array) json_decode($this->array_of_dop_stim_1_1_json, true);
	}
    
    public function getIsTestFinished() : bool
    {
        return $this->number_of_answer > Yii::$app->params['numberOfQuestions'];
    }
    
	/**
     * {@inheritdoc}
     * @see IdentityInterface
     */

frontend/views/site/_search_test_answer.php
<?php

use yii\bootstrap4\Html;
use yii\bootstrap4\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\TestPersonSearch */
/* @var $form yii\bootstrap4\ActiveForm */
?>

<div class="test-answer-search">

    <?php $form = ActiveForm::begin([
        //'action' => ['secret-about'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'test_person_id') ?>

    <?= Html::activeHiddenInput($model, 'answer_number') ?>

    <?= Html::activeHiddenInput($model, 'question_number') ?>

    <?= Html::activeHiddenInput($model, 'created_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('frontend', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('frontend', 'Reset'), ['model' => 'answer'], ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/site/_search_test_person.php
<?php

use yii\bootstrap4\Html;
use yii\bootstrap4\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\TestPersonSearch */
/* @var $form yii\bootstrap4\ActiveForm */
?>

<div class="test-person-search">

    <?php $form = ActiveForm::begin([
        //'action' => ['secret-about'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'surname') ?>

    <?= $form->field($model, 'age') ?>

    <?= $form->field($model, 'gender') ?>

    <?= $form->field($model, 'country') ?>

    <?= Html::activeHiddenInput($model, 'level_of_education') ?>
    
    <?= Html::activeHiddenInput($model, 'type_of_education') ?>
    
    <?= Html::activeHiddenInput($model, 'is_art_education') ?>
    
    <?= Html::activeHiddenInput($model, 'type_of_device') ?>
    
    <?= Html::activeHiddenInput($model, 'array_of_questions_json') ?>
    
    <?= Html::activeHiddenInput($model, 'number_of_answer') ?>
    
    <?= Html::activeHiddenInput($model, 'personal_token') ?>
    
    <?= Html::activeHiddenInput($model, 'auth_key') ?>
    
    <?= Html::activeHiddenInput($model, 'created_at') ?>
    
    <?= Html::activeHiddenInput($model, 'updated_at') ?>
    
    <?= Html::activeHiddenInput($model, 'is_deleted') ?>
    
    <?= Html::activeHiddenInput($model, 'deleted_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('frontend', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('frontend', 'Reset'), ['model' => 'person'], ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/site/about.php
<?php

use yii\grid\GridView;
use yii\data\ArrayDataProvider;

/* @var $this yii\web\View */

$this->title = 'Secret About';

?>
<div class="site-about">
	<?php
		$provider = new ArrayDataProvider([
			'allModels' => common\models\TestPerson::find()->asArray()->all(),
			'pagination' => [
				'pageSize' => 100,
			],
		]);

		echo GridView::widget([
			'dataProvider' => $provider,
			'tableOptions' => ['class' => 'table table-bordered']
		]);
		
		echo '<br><br>';
		
		$provider = new ArrayDataProvider([
			'allModels' => common\models\TestAnswer::find()->asArray()->all(),
			'pagination' => [
				'pageSize' => 100,
			],
		]);

		echo GridView::widget([
			'dataProvider' => $provider,
			'tableOptions' => ['class' => 'table table-bordered']
		]);
	?>
    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/beforeTest.php
<?php

use yii\bootstrap4\Html;

/* @var $this yii\web\View */
/* @var $testPerson common\models\TestPerson */

$t = function ($message, $params = []) {
	return \Yii::t('frontend', $message, $params);
};

$this->title = $t('Before Test');

?>
<div class="row">
	<div class="col-12">
		<p>
			<?= $t('You are take a part in an experiment «Visual attractiveness of a filmframe» test.') ?>
		</p>
    </div>
    <div class="col-12">
        <div class="card col-12">
            <div class="card-body align-content-center" style="padding: 1rem;">
                <h5 style="margin-bottom: 0;"><?= $t('Completed {n} of 25', ['n' => $testPerson->number_of_answer-1]) ?></h5>
            </div>
        </div>
    </div>
    <div class="col-12">
		<p>
            <b><?= $t('Task') ?></b>
            <br>
            <?= $t('You will be offered 25 slides, each slide has 16 film frames.') ?>
            <br>
            <b><?= $t('It is necessary to select all frames with two centers of interest.') ?></b>
            <br>
            <?= $t('The center of interest is an object in the frame, representing a hero or several heroes united by one outline.') ?>
            <br>
            <?= $t('Proceed to the next slide by clicking the "Continue" button.') ?>
		</p>
    </div>
</div>
<?php
    $buttonText = $testPerson->number_of_answer >= 26 ? 'Reset and pass the test again' : 'Continue';
    $buttonText = $testPerson->number_of_answer == 1 ? 'Start test' : $buttonText;
    $buttonUrl = $testPerson->number_of_answer >= 26 ? ['/site/logout'] : ['/site/testme', 'token' => $testPerson->personal_token];
    $buttonClass = $testPerson->number_of_answer >= 26 ? 'btn-danger' : 'btn-primary';
    echo Html::a($t($buttonText), $buttonUrl, ['class' => "float-right btn btn3d $buttonClass"]);
?>

frontend/views/site/congratulations.php
<?php

use yii\bootstrap4\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $testPerson common\models\TestPerson */

$t = function ($message, $params = []) {
	return \Yii::t('frontend', $message, $params);
};

$this->title = $t('Pass the test «Visual attractiveness of a filmframe»');

$user = Yii::$app->user->identity;
$isAnime = Yii::$app->params['testVersion'] === 'anime';
$anotherImageLink = $isAnime ? '/images/bugs-07.png' : '/images/bugs-06.png';
$languagePrefix = Yii::$app->language === 'en-US' ? '/en/' : '/ru/';
$anotherTestLink = $isAnime ? Yii::$app->params['link.photo'] : Yii::$app->params['link.anime'];
$anotherTestLink = str_replace('/en/', $languagePrefix, $anotherTestLink);
$anotherTestLink .= "&surname=$user->surname"
    . "&age=$user->age"
    . "&gender=$user->gender"
    . "&country=$user->country"
    . "&level_of_education=$user->level_of_education"
    . "&type_of_education=$user->type_of_education"
    . "&is_art_education=$user->is_art_education"
    . "&type_of_device=$user->type_of_device"
    . "&color_blindness=$user->color_blindness";
$baseLink = Url::base('https');
?>
<div class="row justify-content-center">
	<div class="col-xs-6 col-xs-6" style="text-align: right">
        <br>
        <h5>
            <b><?= $t('Congratulations, you did it successfully.') ?></b>
		</h5>
		<h4>
			<b><?= $t('Test complete!') ?></b>
		</h4>
		<h4>
			<b><?= $t('Thank you for your patience!') ?></b>
		</h4>
        <h5>
            <?= $t('The Yandex Toloka verification code:') ?> <b class="wf_smile" style="color:#e34a4a">239</b>
        </h5>
	</div>
	<div class="col-xs-6 col-xs-6" >
		<?= Html::img('/images/626_01.png', ['height' => '160px']) ?>
	</div>
</div>
<br>
<div class="row">
    <p>
        <?= $t('You are such a great fellow that you coped with this test, if you still have strength, please take one more test') ?>
    </p>
    <div class="text-center w-100">
        <?= Html::a(Html::img($anotherImageLink, ['width' => '60%']), $anotherTestLink) ?>
        <br>
        <br>
        <?= Html::a('<b>' . $t('Pass second test') . '</b>', $anotherTestLink, ['class' => 'btn btn3d btn-primary', 'style' => '']) ?>
    </div>
    <p>
        <br>
        <p>
            <?= $t('Or end the session and return to ') . Html::a($t('test choice'), ['/site/logout'], ['class' => 'btn btn-sm btn3d btn-danger', 'style' => 'margin-bottom: 3px; opacity:0.8;']) ?> 
        </p>
        <?= $t('We are grateful for your participation! Please share the link to the test with your friends, colleagues, relatives.') ?>
        <br>
        <?= $t('The obtained data will help in studying the visual attractiveness of the filmframe! Follow our publications on the page of') ?>
        <?= Html::a($t('the laboratory of human-computer interaction'), 'https://design.spbstu.ru/laboratory/human_computer/', ['target' => '_blank']) ?>
        <?php if (Yii::$app->params['vk_button']) : ?>
            <script src="https://yastatic.net/share2/share.js"></script>
            <div class="w-100 text-center">
                <?= $t('Share:') ?>
                <div class="ya-share2 " data-url="<?= Url::to(['site/index'], 'https') ?>" data-image="<?=$baseLink?>/images/bugs-08.png" data-curtain data-size="m" data-services="vkontakte,telegram,whatsapp,facebook,twitter"></div>
            </div>
        <?php endif; ?>
    </p>
</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap4\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php

use yii\bootstrap4\Html;
use yii\bootstrap4\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap4\ActiveForm */
/* @var $model common\models\TestPerson */

$t = function ($message) {
	return \Yii::t('frontend', $message);
};

$this->title = 'Why Not Test';
?>
<h1 class="wf-animate-bottom_to_top1" style="text-align: center;"><?= $t('Online test «Visual <span class="wf_smile">attractiveness</span> of the filmframe»') ?></h1>
<div class="row justify-content-center wf-animate-bottom_to_top2">
	<?php $form = ActiveForm::begin([
		'id' => 'form-test-person',
		'options' => [
			'class' => 'col-10 col-lg-10 col-sm-8 ',
		],
		'fieldConfig' => ['template' => "{label}\n<div style=\"min-height: 81px;\">{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}</div>"],
	]); ?>
	<p class="text-center"><?= $t('It is preferable To pass the test, to use a personal computer or laptop.')?>
    <br><br><h4 class="text-center"><?= $t('Fill in information about yourself:') ?></h4>
    <p class="text-center">(<?= $t('The data from this questionnaire will be used exclusively for scientific research. Your data is not disseminated and is not publicly available. The questionnaire can be filled out anonymously with a fictitious nickname instead of a name. Gender, age and educational information must be correct.') ?>)</p>
	<div class="row">
		<div class="col-lg-4 wf-animate-bottom_to_top3">
			<?= $form->field($model, 'surname')->textInput() ?>
            <?= $form->field($model, 'age')->dropDownList($model->agesArray, ['prompt' => $t('Choose...')]) ?>
			<?= $form->field($model, 'gender')->dropDownList($model->gendersArray, ['prompt' => $t('Choose...')]) ?>
		</div>
		<div class="col-lg-4 wf-animate-bottom_to_top4">
			<?= $form->field($model, 'level_of_education')->dropDownList($model->levelsOfEducationArray, ['prompt' => $t('Choose...'), 'onchange' => 'onChangeEducation(event)']) ?>
			<?= $form->field($model, 'type_of_education')->dropDownList($model->typesOfEducationArray, ['prompt' => $t('Choose...')]) ?>
			<?= $form->field($model, 'is_art_education')->dropDownList($model->yesNoArray, ['prompt' => $t('Choose...')]) ?>
		</div>
        <div class="col-lg-4 wf-animate-bottom_to_top5">
            <?= $form->field($model, 'country')->dropDownList($model->countriesArray, ['prompt' => $t('Choose...')]) ?>
            <?= $form->field($model, 'color_blindness')->dropDownList($model->colorBlindnessArray, ['prompt' => $t('Choose...')]) ?>
            <?= $form->field($model, 'type_of_device')->dropDownList($model->devicesArray, ['prompt' => $t('Choose...')]) ?>
        </div>
	</div>
	<div class="w-100"></div>
	<div class="row">
		<div class="col-12 text-center">
			<?= Html::submitButton($t('Continue'), ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
		</div>
	</div>
    <br>
    <div class="row">
        <p>
            <?= $t('This testing is part of a scientific study of the effect of frame elements on the perception of visual information and is carried out by researchers from')?> 
            <?= Html::a($t('the laboratory of human-computer interaction at Peter the Great St. Petersburg Polytechnic University.'), 'https://design.spbstu.ru/laboratory/human_computer/', ['target' => '_blank'])?>
        </p>
    </div>
	<?php ActiveForm::end(); ?>
</div>

frontend/views/site/pre_index.php
<?php

use yii\bootstrap4\Html;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap4\ActiveForm */
/* @var $model common\models\TestPerson */

$t = function ($message) {
	return \Yii::t('frontend', $message);
};

$this->title = 'Why Not Test';
?>
<h1 class="wf-animate-top_to_bottom" style="text-align: center;"><?= $t('Choose which test you want to start:') ?></h1>